name: Artifacts  Demo

on: push

jobs:
  job_1:
    name: Upload Artifacts
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://github.com
        


    steps:
       - name: 'Create a local file'
         run: |
             echo "APP_SECRET: ${{ secrets.APP_SECRET }}" > file.txt


       - uses: actions/upload-artifact@v2
         with:
          name: file
          path: file.txt



  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps: 
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
