name: Artifacts  Demo
on: push

# Upload the artifact
jobs:
  job_1:
    name: Upload Artifact se
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://github.com
        

# Create local file for you to download.
    steps:
       - name: 'Create a local file'
         run: |
             echo "APP_SECRET: ${{ secrets.APP_SECRET }}" > file.txt


       - uses: actions/upload-artifact@v2
         with:
          name: file
          path: file.txt


# This job download the artifact needs the job_1 to run to start.
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps: 
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
